### ISSUE TITLE
Error java.lang.ClassNotFoundException: com.hierynomus.asn1.encodingrules.ASN1Encoder in Rundeck 4.8.0

### ISSUE THREAD

**Issue by Pigueiras** [rundeck-plugins/sshj-plugin#7]
I am trying to use sshj as an alternative of the openssh executor in a Rundeck 4.8.0 (it doesn't have the latest sshj-plugin with the 0.1.3 version but I have the same issue when I use that one) but I'm getting this error when I try to executing anything on the node.

```
Exception in thread "reader" java.lang.NoClassDefFoundError: com/hierynomus/asn1/encodingrules/ASN1Encoder
	at net.schmizz.sshj.signature.SignatureECDSA$Factory256.create(SignatureECDSA.java:44)
	at net.schmizz.sshj.signature.SignatureECDSA$Factory256.create(SignatureECDSA.java:40)
	at com.hierynomus.sshj.key.BaseKeyAlgorithm.newSignature(BaseKeyAlgorithm.java:58)
	at net.schmizz.sshj.transport.kex.AbstractDHG.next(AbstractDHG.java:81)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:378)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:517)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:203)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
Caused by: java.lang.ClassNotFoundException: com.hierynomus.asn1.encodingrules.ASN1Encoder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:58)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:44)
	... 9 more
```

I don't have any experience with gradle and java dependencies, but when I add:

```
 pluginLibs group: 'com.hierynomus', name: 'asn-one', version: '0.6.0', ext: 'jar'
```

in https://github.com/rundeck-plugins/sshj-plugin/blob/main/build.gradle#L43 I am able build it and execute commands with the ssh-sshj executor with no issues in Rundeck. Not sure why I am having this issue because asn-one should be included automatically as a dependency dependency of com.hierynomus.ssh:0.33.0 probably if I trust https://search.maven.org/artifact/com.hierynomus/sshj/0.33.0/jar (as I said, I don't have a lot of experience with these tools 😄 )

Do you have any idea of what could be going on @ltamaster ?

**Comment by krajster** [comment]
I have same issue after upgrade rundeck from 4.8.0 to 4.9.0.

My Rundeck detail

    Rundeck version: 4.9.0
    install type: WAR
    OS Name/version: Windows 2019
    DB Type/version: MSSQL 2019
    sshj-plugin-v0.1.3
    
    When executing on windows node with ssh
```
Exception in thread "sshj-Reader-srv-001.local.lan/10.0.1.12:22" java.lang.NoClassDefFoundError: com/hierynomus/asn1/encodingrules/ASN1Encoder
	at net.schmizz.sshj.signature.SignatureECDSA$Factory256.create(SignatureECDSA.java:40)
	at net.schmizz.sshj.signature.SignatureECDSA$Factory256.create(SignatureECDSA.java:36)
	at com.hierynomus.sshj.key.BaseKeyAlgorithm.newSignature(BaseKeyAlgorithm.java:58)
	at net.schmizz.sshj.transport.kex.AbstractDHG.next(AbstractDHG.java:82)
	at net.schmizz.sshj.transport.KeyExchanger.handle(KeyExchanger.java:388)
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:485)
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113)
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200)
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60)
Caused by: java.lang.ClassNotFoundException: com.hierynomus.asn1.encodingrules.ASN1Encoder
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:58)
	at com.dtolabs.rundeck.core.plugins.LocalFirstClassLoader.loadClass(LocalFirstClassLoader.java:44)
	... 9 more
[sshj-ssh] TransportException: null
Failed: Unknown: null
```

`Java version 1.8.0_361`

**Comment by MegaDrive68k** [comment]
Hi folks!

Issue Reproduced, weird, on Linux/Mac this plugin works but on Windows fails.

Thanks for your feedback!

**Comment by Pigueiras** [comment]
> Hi folks!
> 
> Issue Reproduced, weird, on Linux/Mac this plugin works but on Windows fails.
> 
> Thanks for your feedback!

I'm getting this on Linux too

**Comment by Pigueiras** [comment]
Now it's working with the v0.1.6 version that comes with Rundeck 4.11.0! 😄  It was probably fixed with the commits in https://github.com/rundeck/rundeck/issues/8121
